defaults:
  -
    scope:
      path: ''

    values:
      layout: default

  -
    scope:
      type: posts
      path: manicures

    values:
      layout: manicure
      parent: manicures

permalink: pretty
